### ISSUE TITLE
Language not auto-detected, or highlighting is broken...

### ISSUE THREAD

**Issue by terheyden** [fara/gmail-highlight#6]
I created a new gmail draft, then pasted the following, with no formatting:

```
public class CloneTest {
    @Test
    public void test() throws CloneNotSupportedException {

        Beta beta = new Beta(
            "name",
            Arrays.asList("a", "b", "c"),
            new String[] {"secret"},
            "bID",
            new SimpleEntry<>(6, "bert")
            );

        Beta beta01 = (Beta) beta.clone();

        Assert2.that()
            .eq(beta.aName, beta01.aName)
            .eq(beta.getaSecret(), beta01.getaSecret())
            .eq(beta.getbEntry(), beta01.getbEntry());
    }
}
```

When I clicked the "Syntax Highlight" format button, there was very little highlighting, and what was highlighted was inconsistent - see attached screenshot. It may have just not detected Java correctly? I'm not sure.

![2017-03-17_07-37-03](https://cloud.githubusercontent.com/assets/984174/24048150/2e9128ee-0ae5-11e7-85e2-a41f92eba4da.gif)

**Comment by fara** [comment]
Highlight.js heuristic seems to fail to autodetect the right language on some snippets (this one is being recognized as Perl). Will add a dropdown list to the toolbar button in order to force most popular languages.

**Comment by terheyden** [comment]
Thanks!

**Comment by ktryber** [comment]
leaving an answer here for other users that may experience this. 

@fara added functionality so that if you type your desired language in the first line, then your code after, then highlight everything. Then click the toolbar button and that will define the language that you are using. 

example:

```
python
def test_function():
    return "this is python"
```
