### ISSUE TITLE
gmail-highlight doesn't work any more

### ISSUE THREAD

**Issue by rmunk** [fara/gmail-highlight#7]
When I click on a _Syntax Highlight_ button nothing happens. It was working before.

- **Google Chrome** Version 61.0.3163.100 (Official Build) (64-bit)
- **macOS Sierra** Version 10.12.6 (16G29)

**Comment by cachrisman** [comment]
same for me...

- **Google Chrome** version 61.0.3163.100
- **macOS Sierra** version 10.12.6 (16G29)

![image](https://user-images.githubusercontent.com/6521666/31025387-56327e3c-a4f7-11e7-92c1-e42b4e557452.png)

> Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'nonce-PfGOuvg8JXCSygkcdXOWOhzdPVA' 'strict-dynamic' 'unsafe-eval' 'unsafe-inline' https: 'report-sample'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.

**Comment by KidA001** [comment]
Same here

Chrome Version 61.0.3163.100 (Official Build) (64-bit)
OSX Sierra 10.12.6

Chrome inspector error
```
Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'nonce-8KsY/Wqz0v+7pwSrL4eCIl+SrX0' 'strict-dynamic' 'unsafe-eval' 'unsafe-inline' https: 'report-sample'". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
```

**Comment by KidA001** [comment]
A temporary and meh fix is to install `https://chrome.google.com/webstore/detail/disable-content-security/ieelmcmcagommplceebfedjlakkhpden/related?hl=en` You can toggle disabling the content security policy.

Install, disable CSP, refresh gmail and syntax highlighting works again.

**Comment by fara** [comment]
This is fixed now with a workaround by @markustauscher. Thanks everyone for reporting and thanks Markus for your help.
You should see version 1.4 published in the store with the update.
